services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"    # Jenkins على منفذ 9090
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock # its' allow us to use docker engine inside jenkins -- there is connection btw them
    user: root # we add user root so we can install docker cli
    command: >
      bash -c "
      apt-get update &&
      apt-get install -y docker.io &&
      /usr/bin/tini -- /usr/local/bin/jenkins.sh
      "
  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8080"    # تطبيق Spring Boot على 8081
    depends_on:
      - jenkins

volumes:
  jenkins_home: