services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "9090:8080"    # Jenkins على منفذ 9090
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home

  spring-app:
    build: .
    container_name: spring-app
    ports:
      - "8081:8080"    # تطبيق Spring Boot على 8081
    depends_on:
      - jenkins

volumes:
  jenkins_home:
